### ISSUE TITLE
state proxy for nobles

### ISSUE THREAD

**Issue by dilarakkl** [kadron/splendor-prolog#5]
I believe there are no stateproxy for getting the nobles of the board. 

stateProxy(game, nobles, L) :-
    findall(X,nobles(X),L).

should be added to the code.

Also cards are sent by stateProxy are only ID s so we do not have information about their gems requirements and bonuses.

**Comment by basarane** [comment]
nobles are added to stateProxy as proposed. 

There is a `card` predicate exported by Splendor module which can be used to get info about a card given its ID. It is public, you can use the following predicate in your player files. 

```
card(X,Gems-BonusColor-Point).
```
- `Gems` is the list of gems required to get the card
- `BonusColor` is the color of bonus 
- `Point` is the point obtained by buying this card

This was a design decision. When I profiled the game in Prolog, I realized that the time spent on asserts and retracts dominates the total CPU time. Instead of asserting a large structure for cards, I choose to assert only IDs to save both memory and CPU time. I think this helped. However I'm not sure if this is also true for the cases that need a lot of card data fetches.
